"""Filesystem layout for SambaEval data.

All state lives under a single data directory (no database). The directory is
resolved from the ``SAMBAEVAL_DATA_DIR`` environment variable when set, falling
back to ``<repo>/sambaeval/data`` (two parents up from this package).

Private scope
-------------
Alongside the public tree, a mirrored **private** tree lives under
``data/private/`` (``experiments/``, ``datasets/``, ``scorers/``, ``results/``).
It is gitignored, so private experiments and everything they touch — the
dataset, scorer, and the run outputs they produce — stay local. An experiment
is "private" purely by living in ``data/private/experiments/``; its runs are
written under ``data/private/results/`` so they are gitignored too. The public
tree is the default for writes; the private tree is opt-in per experiment.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional


def _default_data_dir() -> Path:
    # paths.py lives at sambaeval/backend/sambaeval/paths.py
    # parents[2] == the product directory "sambaeval", so /data sits beside app/.
    return Path(__file__).resolve().parents[2] / "data"


def data_dir() -> Path:
    env = os.environ.get("SAMBAEVAL_DATA_DIR")
    return Path(env).expanduser().resolve() if env else _default_data_dir()


def private_dir() -> Path:
    """Root of the gitignored private tree, mirroring the public data dir."""
    return data_dir() / "private"


# --------------------------------------------------------------------------- #
# Public subdirs (the default target for writes)
# --------------------------------------------------------------------------- #
def experiments_dir() -> Path:
    return data_dir() / "experiments"


def datasets_dir() -> Path:
    return data_dir() / "datasets"


def results_dir() -> Path:
    return data_dir() / "results"


def scorers_dir() -> Path:
    return data_dir() / "scorers"


# --------------------------------------------------------------------------- #
# Private subdirs (gitignored; opt-in per experiment)
# --------------------------------------------------------------------------- #
def private_experiments_dir() -> Path:
    return private_dir() / "experiments"


def private_datasets_dir() -> Path:
    return private_dir() / "datasets"


def private_results_dir() -> Path:
    return private_dir() / "results"


def private_scorers_dir() -> Path:
    return private_dir() / "scorers"


# --------------------------------------------------------------------------- #
# Scan lists (public first, then private) + resolvers
# --------------------------------------------------------------------------- #
def experiments_dirs() -> list[Path]:
    return [experiments_dir(), private_experiments_dir()]


def datasets_dirs() -> list[Path]:
    return [datasets_dir(), private_datasets_dir()]


def scorers_dirs() -> list[Path]:
    return [scorers_dir(), private_scorers_dir()]


def providers_file() -> Path:
    return data_dir() / "providers.json"


def pricing_defaults_file() -> Path:
    # Provider/model default token prices, generated by scripts/update_pricing.py.
    return data_dir() / "pricing_defaults.json"


def scorer_file_path(name: str, *, private: bool = False) -> Path:
    # basename guards against path traversal.
    safe = os.path.basename(name)
    root = private_scorers_dir() if private else scorers_dir()
    return root / f"{safe}.json"


def find_scorer_file(name: str) -> Optional[Path]:
    """The scorer file for ``name`` in whichever tree holds it (public wins)."""
    safe = os.path.basename(name)
    for d in scorers_dirs():
        p = d / f"{safe}.json"
        if p.exists():
            return p
    return None


def experiment_file_path(experiment_id: str, *, private: bool = False) -> Path:
    root = private_experiments_dir() if private else experiments_dir()
    return root / f"{experiment_id}.json"


def find_experiment_file(experiment_id: str) -> Optional[Path]:
    """The experiment file for ``experiment_id`` in whichever tree holds it."""
    for d in experiments_dirs():
        p = d / f"{experiment_id}.json"
        if p.exists():
            return p
    return None


def experiment_is_private(experiment_id: str) -> bool:
    """True when the experiment lives in the private tree (its runs go there)."""
    return (private_experiments_dir() / f"{experiment_id}.json").exists()


def dataset_file_path(name: str, *, private: bool = False) -> Path:
    safe = os.path.basename(name)
    root = private_datasets_dir() if private else datasets_dir()
    return root / safe


def find_dataset_file(name: str) -> Optional[Path]:
    """The dataset file for ``name`` in whichever tree holds it (public wins)."""
    safe = os.path.basename(name)
    for d in datasets_dirs():
        p = d / safe
        if p.exists():
            return p
    return None


def experiment_runs_dir(experiment_id: str) -> Path:
    """Directory that NEW runs are written under: the private results tree for
    a private experiment (so its outputs stay gitignored), else public. Privacy
    wins over any pre-existing public runs so a private experiment never leaks
    new run results into the committed tree.
    """
    root = private_results_dir() if experiment_is_private(experiment_id) else results_dir()
    return root / experiment_id


def experiment_runs_dirs(experiment_id: str) -> list[Path]:
    """Both candidate run dirs (public, then private) for listing / lookup.

    An experiment that was toggled between scopes may have older runs in one
    tree and newer runs in the other; callers union these so no run is hidden.
    """
    return [results_dir() / experiment_id, private_results_dir() / experiment_id]


def run_dir(experiment_id: str, run_id: str) -> Path:
    """The dir for one run. An existing run resolves to whichever tree holds it;
    a brand-new run goes under the experiment's scoped tree.
    """
    for d in experiment_runs_dirs(experiment_id):
        p = d / run_id
        if p.exists():
            return p
    return experiment_runs_dir(experiment_id) / run_id


def run_results_path(experiment_id: str, run_id: str) -> Path:
    return run_dir(experiment_id, run_id) / "results.csv"


def run_meta_path(experiment_id: str, run_id: str) -> Path:
    return run_dir(experiment_id, run_id) / "run.json"


def run_errors_path(experiment_id: str, run_id: str) -> Path:
    return run_dir(experiment_id, run_id) / "errors.json"


def run_experiment_snapshot_path(experiment_id: str, run_id: str) -> Path:
    return run_dir(experiment_id, run_id) / "experiment.json"
