#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

#######################################
# Logging
#######################################
info() {
  echo -e "\033[1;32m[INFO] $*\033[0m"
}

error() {
  echo -e "\033[1;31m[ERROR] $*\033[0m" >&2
  exit 1
}

#######################################
# Usage
#######################################
show_help() {
  cat <<EOF
Usage:
  $0 -i <inventory.yaml> [OPTIONS]

Required:
  -i <inventory.yaml>  Inventory YAML file with chart images (from generate_inventory.sh)

Options:
  -b <bundle.tar.zst>  Bundle tar.zst file with pre-pulled images (from bundle_images.sh) [required if not --dry-run]
  -c <creds.json>      Credentials file for harbor registry [required if not --dry-run]
  -o, --output         Output file for harbor destination images mapping (YAML format with source/destination keys)
  -d, --dry-run        Show what would be pushed without actually pushing
  -h, --help           Show this help message

Inventory YAML format (e.g., inventory.yaml):
  charts:
    - name: sambastack
      version: 0.3.465
      path: .
      images:
        - docker.io/image:tag
        - registry.example.com/image:tag
      charts:
        - name: redis
          version: 27.0.15
          repository: oci://registry-1.docker.io/bitnamicharts
        - name: openebs
          version: 4.5.1
          repository: https://openebs.github.io/openebs

Bundle tar.zst format:
  - Generated by bundle_images.sh (e.g., stack-0.3.465.tar.zst)
  - Contains pre-pulled image tar files (image__tag.tar)
  - Images listed in inventory file must match bundle images

creds.json format:
{
  "docker": {
    "url": "harbor.registry.local",
    "project": "library",
    "username": "admin",
    "password": "password"
  }
}

Examples:
  # Dry-run: Show what would be pushed and generate seed images mapping
  $0 -i inventory.yaml -o seed_images.yaml -d

  # Actual: Push from pre-pulled bundle to Harbor (air-gapped environment)
  $0 -i inventory.yaml -b stack-0.3.465.tar.zst -c creds.json
EOF
  exit 1
}

#######################################
# Args
#######################################
DRY_RUN=false
INVENTORY_FILE=""
CREDS_FILE=""
BUNDLE_FILE=""
OUTPUT_FILE=""

[[ $# -eq 0 ]] && show_help

while [[ $# -gt 0 ]]; do
  case "$1" in
    -i) INVENTORY_FILE="$2"; shift 2 ;;
    -c) CREDS_FILE="$2"; shift 2 ;;
    -b) BUNDLE_FILE="$2"; shift 2 ;;
    -o|--output) OUTPUT_FILE="$2"; shift 2 ;;
    -d|--dry-run) DRY_RUN=true; shift ;;
    -h|--help) show_help ;;
    *) error "Unknown option: $1" ;;
  esac
done

#######################################
# Validation
#######################################
[[ -n "${INVENTORY_FILE:-}" ]] || error "Missing -i (inventory file)"
[[ -f "$INVENTORY_FILE" ]] || error "Inventory file not found: $INVENTORY_FILE"

# In dry-run mode, bundle and creds are optional
if [[ "$DRY_RUN" != "true" ]]; then
  [[ -n "${BUNDLE_FILE:-}" ]] || error "Missing -b (bundle file) [required unless --dry-run]"
  [[ -f "$BUNDLE_FILE" ]] || error "Bundle file not found: $BUNDLE_FILE"
  [[ "$BUNDLE_FILE" == *.tar.zst ]] || error "Bundle file must be .tar.zst format"
  [[ -n "${CREDS_FILE:-}" ]] || error "Missing -c (credentials file) [required unless --dry-run]"
  [[ -f "$CREDS_FILE" ]] || error "Credentials file not found: $CREDS_FILE"
fi

# Use Bazel-provided yq if available, else fall back to PATH
YQ="${YQ:-yq}"

# Check for required commands based on mode
if [[ "$DRY_RUN" == "true" ]]; then
  for cmd in jq; do
    command -v "$cmd" >/dev/null 2>&1 || error "$cmd is required"
  done
else
  for cmd in crane jq zstd tar helm; do
    command -v "$cmd" >/dev/null 2>&1 || error "$cmd is required"
  done
fi
command -v "$YQ" >/dev/null 2>&1 || error "yq is required (set \$YQ or install yq on PATH)"

#######################################
# Registry creds
#######################################
REGISTRY_URL=""
REGISTRY_PROJECT=""
REGISTRY_USER=""
REGISTRY_PASS=""

if [[ "$DRY_RUN" != "true" ]]; then
  REGISTRY_URL=$(jq -r '.docker.url' "$CREDS_FILE")
  REGISTRY_PROJECT=$(jq -r '.docker.project // .docker.repo' "$CREDS_FILE")  # Support both "project" and "repo"
  REGISTRY_USER=$(jq -r '.docker.username' "$CREDS_FILE")
  REGISTRY_PASS=$(jq -r '.docker.password' "$CREDS_FILE")
  [[ -n "$REGISTRY_URL" && -n "$REGISTRY_PROJECT" ]] || error "Invalid creds file: missing url or project"
else
  # In dry-run mode, provide defaults
  REGISTRY_URL="harbor.registry.local"
  REGISTRY_PROJECT="library"
fi

#######################################
# Setup work directory
#######################################
WORK_DIR=$(mktemp -d -t "seed.XXXXXX")
trap 'rm -rf "$WORK_DIR"' EXIT
INTERRUPTED=false
trap 'INTERRUPTED=true' INT
info "Using work directory: $WORK_DIR"

IMAGE_TAR_MAP="$WORK_DIR/image_tar_map.txt"
BUNDLE_DIR="$WORK_DIR/bundle"
ORIGINAL_IMGS="$WORK_DIR/original_images.txt"
HARBOR_IMGS="$WORK_DIR/harbor_images.txt"

# Only setup bundle directory and extract if not in dry-run mode
if [[ "$DRY_RUN" != "true" ]]; then
  mkdir -p "$BUNDLE_DIR"

  info "Extracting bundle: $BUNDLE_FILE"

  # Decompress and extract
  zstd -dc "$BUNDLE_FILE" | tar -x -C "$BUNDLE_DIR"

  # Find all image tar files and create mapping
  info "Discovering image tar files in bundle..."
  while IFS= read -r tar_file; do
    # Convert filename back to image name
    # Format: image__tag.tar -> image:tag
    filename=$(basename "$tar_file" .tar)
    img_name="${filename//__/:}"
    echo "$img_name|$tar_file" >> "$IMAGE_TAR_MAP"
  done < <(find "$BUNDLE_DIR" -maxdepth 1 -name "*.tar" -type f)

  BUNDLE_IMAGE_COUNT=$(grep -c . "$IMAGE_TAR_MAP" 2>/dev/null || echo 0)
  info "Bundle extracted with $BUNDLE_IMAGE_COUNT image tar files"
fi

#######################################
# Extract images from inventory
#######################################
extract_images() {
  local inventory="$1"
  # Use yq to extract all images from all charts in the inventory
  "$YQ" eval '.charts[].images[]' "$inventory" 2>/dev/null || echo ""
}

#######################################
# Transform image URL to harbor URL
# Handles different registry formats:
#   - docker.io/org/image:tag          -> harbor/project/org/image:tag
#   - quay.io/org/image:tag            -> harbor/project/org/image:tag
#   - registry.k8s.io/org/image:tag    -> harbor/project/org/image:tag
#   - us-west2-docker.pkg.dev/proj/repo/org/image:tag  -> harbor/project/org/image:tag
#   - image:tag or org/image:tag       -> harbor/project/image:tag or harbor/project/org/image:tag
#######################################
transform_to_harbor_url() {
  local source_image="$1"
  local registry_url="$2"
  local project="$3"

  local image_path
  local is_private=false

  # Determine if image is PRIVATE (pkg.dev WITHOUT /public/)
  # Everything else is treated as PUBLIC (external registries + pkg.dev with /public/)
  # Private images = sambastack apps that are proprietary
  # Public images = external packages (keycloak, openebs, redis, etc.) or explicit public pkg.dev images
  if [[ "$source_image" =~ pkg\.dev ]] && ! [[ "$source_image" =~ /public/ ]]; then
    is_private=true
  fi

  # Special handling for docker.pkg.dev URLs
  # Format: <region>-docker.pkg.dev/<project-id>/<repo>/<org>/<image>:<tag>
  # Extract just the last path components (org/image or image)
  if [[ "$source_image" =~ pkg\.dev ]]; then
    # Remove first two path components (registry + project-id)
    image_path="${source_image#*/}"        # Remove registry base (region-docker.pkg.dev)
    image_path="${image_path#*/}"          # Remove project-id
    # Result now: repo/org/image:tag or repo/image:tag
    # For pkg.dev, we want to simplify by removing the repo prefix (e.g., oci-us-west2-fastcoe-dev)
    # Keep org/image structure if it exists, else just image
    image_path="${image_path#*/}"          # Remove repo component (oci-us-west2-fastcoe-dev)

    # Remove /public/ prefix from image_path if present (it's now just the image part)
    image_path="${image_path#public/}"
  else
    # Check if first component looks like a registry hostname (contains a dot)
    # e.g., docker.io, quay.io, ghcr.io, registry.k8s.io
    local first_component="${source_image%%/*}"
    if [[ "$first_component" =~ \. ]]; then
      # Looks like a registry hostname - remove it
      image_path="${source_image#*/}"
    else
      # Image name without registry (e.g., nats:tag, openebs/image:tag)
      image_path="$source_image"
    fi
  fi

  # Route to appropriate harbor path based on whether it's private or public
  if [[ "$is_private" == "true" ]]; then
    # Private images (sambastack apps) go to project path (e.g., harbor.registry.local/library/sambastack/api-model-router:tag)
    # image_path already contains "sambastack/" prefix for pkg.dev private images
    echo "${registry_url}/${project}/${image_path}"
  else
    # Public images (external packages) go to public path (e.g., harbor.registry.local/library/public/keycloak:tag)
    echo "${registry_url}/${project}/public/${image_path}"
  fi
}

#######################################
# Transform a chart dependency to its harbor OCI destination.
# Dependency charts are external packages, so they route to the public/
# path like public images: harbor/project/public/<chart-name>
# (the chart version is carried as the OCI tag by helm/crane).
#######################################
transform_chart_to_harbor_url() {
  local chart_name="$1"
  local registry_url="$2"
  local project="$3"

  echo "${registry_url}/${project}/public/${chart_name}"
}

#######################################
# Extract and transform images
#######################################
info "Extracting images from inventory"

while IFS= read -r img; do
  [[ -z "$img" ]] && continue
  echo "$img" >> "$ORIGINAL_IMGS"
  harbor_url=$(transform_to_harbor_url "$img" "$REGISTRY_URL" "$REGISTRY_PROJECT")
  echo "$harbor_url" >> "$HARBOR_IMGS"
done < <("$YQ" eval '.charts[].images[]' "$INVENTORY_FILE" 2>/dev/null)

# Count images
IMAGE_COUNT=$(wc -l < "$ORIGINAL_IMGS" 2>/dev/null || echo 0)
IMAGE_COUNT=$((IMAGE_COUNT))

[[ $IMAGE_COUNT -gt 0 ]] || error "No images found in inventory"

#######################################
# Extract and transform helm charts
#
# Each chart dependency is emitted as "repository|name|version|harbor_dest".
# Charts are deduplicated on repository+name+version (the same subchart may
# appear multiple times in the inventory, e.g. aliased redis dependencies).
#######################################
CHART_TSV="$WORK_DIR/charts.tsv"
: > "$CHART_TSV"

info "Extracting charts from inventory"
while IFS=$'\t' read -r chart_repo chart_name chart_version; do
  [[ -z "$chart_name" ]] && continue
  harbor_chart=$(transform_chart_to_harbor_url "$chart_name" "$REGISTRY_URL" "$REGISTRY_PROJECT")
  echo "${chart_repo}|${chart_name}|${chart_version}|${harbor_chart}" >> "$CHART_TSV"
done < <("$YQ" eval '.charts[].charts[] | [.repository, .name, .version] | @tsv' "$INVENTORY_FILE" 2>/dev/null)

# Deduplicate identical chart entries while preserving order
if [[ -s "$CHART_TSV" ]]; then
  CHART_TSV_DEDUP="$WORK_DIR/charts.dedup.tsv"
  awk '!seen[$0]++' "$CHART_TSV" > "$CHART_TSV_DEDUP"
  mv "$CHART_TSV_DEDUP" "$CHART_TSV"
fi

CHART_COUNT=$(grep -c . "$CHART_TSV" 2>/dev/null || echo 0)
CHART_COUNT=$((CHART_COUNT))

#######################################
# Show images BEFORE
#######################################
info "=== IMAGES TO BE PUSHED ==="
info "Total: $IMAGE_COUNT images"
info "Original images source:"
cat "$ORIGINAL_IMGS" | sed 's/^/  /'
info "Harbor destination images:"
cat "$HARBOR_IMGS" | sed 's/^/  /'

if [[ $CHART_COUNT -gt 0 ]]; then
  info "=== CHARTS TO BE PUSHED ==="
  info "Total: $CHART_COUNT charts"
  while IFS='|' read -r chart_repo chart_name chart_version harbor_chart; do
    [[ -z "$chart_name" ]] && continue
    info "  ${chart_repo}/${chart_name}:${chart_version} -> ${harbor_chart}:${chart_version}"
  done < "$CHART_TSV"
fi

#######################################
# Output images mapping to YAML if requested
#######################################
if [[ -n "$OUTPUT_FILE" ]]; then
  info "Writing images mapping to: $OUTPUT_FILE"

  # Create YAML output matching test_inventory.yaml structure with harbor destination images
  # Sort images for deterministic output
  {
    echo "charts:"
    echo "  - name: sambastack"
    echo "    version: 1.0.0"
    echo "    path: ."
    echo "    images:"
    sort "$HARBOR_IMGS" | while IFS= read -r destination; do
      echo "      - $destination"
    done
    if [[ $CHART_COUNT -gt 0 ]]; then
      echo "    charts:"
      # Sort by harbor destination for deterministic output
      sort -t'|' -k4 "$CHART_TSV" | while IFS='|' read -r chart_repo chart_name chart_version harbor_chart; do
        [[ -z "$chart_name" ]] && continue
        echo "      - name: $chart_name"
        echo "        version: $chart_version"
        echo "        repository: $harbor_chart"
      done
    fi
  } > "$OUTPUT_FILE"

  info "✓ Images mapping written to $OUTPUT_FILE"
fi

#######################################
# Dry-run mode
#######################################
if [[ "$DRY_RUN" == "true" ]]; then
  info "DRY-RUN: Skipping authentication and push"
  info "DRY-RUN: Would push $IMAGE_COUNT images"
  exit 0
fi

#######################################
# Auth
#######################################
info "Authenticating to $REGISTRY_URL"
crane auth login "$REGISTRY_URL" \
  -u "$REGISTRY_USER" \
  -p "$REGISTRY_PASS" \
  --insecure

#######################################
# Push images from bundle
#######################################
PUSH_SUCCESS=0
PUSH_FAILED=0

info "Starting image push to Harbor registry..."

# Read files into arrays
mapfile -t original_images < "$ORIGINAL_IMGS"
mapfile -t harbor_images < "$HARBOR_IMGS"

# Get image count
image_count=${#original_images[@]}

# Iterate over each index
for ((i = 0; i < image_count; i++)); do
  info "Pushing === $i ==="

  source_img="${original_images[$i]}"
  harbor_img="${harbor_images[$i]}"

  [[ -z "$source_img" || -z "$harbor_img" ]] && continue

  # Extract image name (last component after /) and tag (after :)
  image_with_tag="${source_img##*/}"  # e.g., redis_exporter:v1.59.0
  image_name="${image_with_tag%%:*}"  # e.g., redis_exporter
  image_tag="${image_with_tag#*:}"    # e.g., v1.59.0

  # Construct tar file path: image_name__image_tag.tar
  tar_file="$BUNDLE_DIR/${image_name}__${image_tag}.tar"

  if [[ ! -f "$tar_file" ]]; then
    error "Tar file not found: $tar_file (for image: $source_img)"
  fi

  info "Pushing: $source_img -> $harbor_img"

  # Push image from tar file to harbor
  if crane push "$tar_file" "$harbor_img" --insecure; then
    info "✓ Successfully pushed: $harbor_img"
    PUSH_SUCCESS=$((PUSH_SUCCESS + 1))
  else
    # If bash received SIGINT while crane was running, exit immediately;
    # the EXIT trap will clean up $WORK_DIR.
    $INTERRUPTED && exit 130
    info "✗ Failed to push: $harbor_img"
    PUSH_FAILED=$((PUSH_FAILED + 1))
  fi

done

info "=== PUSH SUMMARY ==="
info "Total pushed: $IMAGE_COUNT"
info "Successful: $PUSH_SUCCESS"
info "Failed: $PUSH_FAILED"

if [[ $PUSH_FAILED -gt 0 ]]; then
  error "Some images failed to push ($PUSH_FAILED/$IMAGE_COUNT)"
fi

info "All images successfully pushed to Harbor!"

#######################################
# Push helm charts to Harbor OCI registry
#
# Charts are not part of the image bundle tar; they are pulled from their
# source repositories and pushed to Harbor's OCI registry. OCI-hosted charts
# (oci://...) are pulled directly; classic HTTP helm repos are pulled via
# `helm pull <name> --repo <url> --version <ver>`.
#######################################
if [[ $CHART_COUNT -gt 0 ]]; then
  info "Authenticating helm to $REGISTRY_URL"
  echo "$REGISTRY_PASS" | helm registry login "$REGISTRY_URL" \
    -u "$REGISTRY_USER" --password-stdin --insecure

  CHART_PULL_DIR="$WORK_DIR/charts"
  mkdir -p "$CHART_PULL_DIR"

  CHART_PUSH_SUCCESS=0
  CHART_PUSH_FAILED=0

  info "Starting chart push to Harbor registry..."

  while IFS='|' read -r chart_repo chart_name chart_version harbor_chart; do
    [[ -z "$chart_name" ]] && continue

    info "Pulling chart: ${chart_repo}/${chart_name}:${chart_version}"
    rm -f "$CHART_PULL_DIR"/*.tgz 2>/dev/null || true

    if [[ "$chart_repo" == oci://* ]]; then
      pull_ok=false
      helm pull "${chart_repo}/${chart_name}" --version "$chart_version" \
        --destination "$CHART_PULL_DIR" && pull_ok=true
    else
      pull_ok=false
      helm pull "$chart_name" --repo "$chart_repo" --version "$chart_version" \
        --destination "$CHART_PULL_DIR" && pull_ok=true
    fi

    if [[ "$pull_ok" != "true" ]]; then
      $INTERRUPTED && exit 130
      info "✗ Failed to pull chart: ${chart_repo}/${chart_name}:${chart_version}"
      CHART_PUSH_FAILED=$((CHART_PUSH_FAILED + 1))
      continue
    fi

    chart_tgz=$(find "$CHART_PULL_DIR" -maxdepth 1 -name "*.tgz" -type f | head -n 1)
    if [[ -z "$chart_tgz" ]]; then
      info "✗ No chart tarball produced for: ${chart_name}:${chart_version}"
      CHART_PUSH_FAILED=$((CHART_PUSH_FAILED + 1))
      continue
    fi

    # helm push targets the OCI repository (namespace); the chart name and
    # version tag are derived from the chart tarball itself. The destination
    # namespace is harbor_chart with the trailing chart-name segment removed.
    harbor_namespace="${harbor_chart%/*}"

    info "Pushing chart: $chart_tgz -> oci://${harbor_namespace}"
    if helm push "$chart_tgz" "oci://${harbor_namespace}" --insecure-skip-tls-verify; then
      info "✓ Successfully pushed chart: ${harbor_chart}:${chart_version}"
      CHART_PUSH_SUCCESS=$((CHART_PUSH_SUCCESS + 1))
    else
      $INTERRUPTED && exit 130
      info "✗ Failed to push chart: ${harbor_chart}:${chart_version}"
      CHART_PUSH_FAILED=$((CHART_PUSH_FAILED + 1))
    fi
  done < "$CHART_TSV"

  info "=== CHART PUSH SUMMARY ==="
  info "Total charts: $CHART_COUNT"
  info "Successful: $CHART_PUSH_SUCCESS"
  info "Failed: $CHART_PUSH_FAILED"

  if [[ $CHART_PUSH_FAILED -gt 0 ]]; then
    error "Some charts failed to push ($CHART_PUSH_FAILED/$CHART_COUNT)"
  fi

  info "All charts successfully pushed to Harbor!"
fi
