---
apiVersion: sambanova.ai/v1alpha1
kind: BundleTemplate
metadata:
  name: bt-multi
spec:
  models:
    Meta-Llama-3.1-8B-Instruct:
      experts:
        "4k":
          configs:
            - pef: llama-3.1-8b-instruct-ss4k-bs1:1
    Meta-Llama-3.1-70B-Instruct:
      experts:
        "4k":
          configs:
            - pef: llama-3.1-70b-instruct-ss4k-bs1:1
---
apiVersion: sambanova.ai/v1alpha1
kind: Bundle
metadata:
  name: b-multi
spec:
  template: bt-multi
